ALTER TABLE DETALLEPEDIDOMERC ADD CONSEC_PADRE_GUIA INT NULL
ALTER TABLE DETALLEPEDIDOMERC ADD CVE_ART_GUIA VARCHAR(16) NULL
ALTER TABLE DETALLEPEDIDOMERC ADD PRECIO_GUIA FLOAT NULL
ALTER TABLE DETALLEPEDIDOMERC ADD ASIG_PEDIDO_GUIA BIT NULL
ALTER TABLE DETALLEPEDIDOMERC ADD NUM_GUIA VARCHAR(50) NULL
