USE [SWYRA]
GO

/****** Object:  Table [dbo].[INVENTARIOPRECIOS]    Script Date: 08/05/2018 08:56:53 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INVENTARIOPRECIOS](
	[CVE_ART] [varchar](16) NOT NULL,
	[CVE_PRECIO] [int] NOT NULL,
	[PRECIO] [float] NULL,
 CONSTRAINT [PK_INVENTARIOPRECIOS] PRIMARY KEY CLUSTERED 
(
	[CVE_ART] ASC,
	[CVE_PRECIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


