USE [SWYRA]
GO

DROP TABLE [dbo].[INVENTARIOPRESENT]

/****** Object:  Table [dbo].[INVENTARIOPRESENT]    Script Date: 24/01/2018 04:19:31 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INVENTARIOPRESENT](
	[CVE_ART] [varchar](16) NOT NULL,
	[DESCR] [varchar](40) NOT NULL,
	[CANT_PIEZAS_1] [int] NULL,
	[CODIGO_BARRA_1] [varchar](20) NULL,
	[CANT_PIEZAS_2] [int] NULL,
	[CODIGO_BARRA_2] [varchar](20) NULL,
	[CANT_PIEZAS_3] [int] NULL,
	[CODIGO_BARRA_3] [varchar](20) NULL,
	[CANT_PIEZAS_4] [int] NULL,
	[CODIGO_BARRA_4] [varchar](20) NULL,
	[CANT_PIEZAS_5] [int] NULL,
	[CODIGO_BARRA_5] [varchar](20) NULL,
	[CANT_PIEZAS_6] [int] NULL,
	[CODIGO_BARRA_6] [varchar](20) NULL,
	[CANT_PIEZAS_7] [int] NULL,
	[CODIGO_BARRA_7] [varchar](20) NULL,
	[CANT_PIEZAS_8] [int] NULL,
	[CODIGO_BARRA_8] [varchar](20) NULL,
	[CANT_PIEZAS_9] [int] NULL,
	[CODIGO_BARRA_9] [varchar](20) NULL,
	[ACTIVO] [bit] NULL,
 CONSTRAINT [PK_INVENTARIOPRESENT] PRIMARY KEY CLUSTERED 
(
	[CVE_ART] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


